// <auto-generated />
using System;
using Appointment.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appointment.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230416031523_Migra2")]
    partial class Migra2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointment.Shared.Entities.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("role_id");

                    b.HasIndex("role_id")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Appointment.Shared.Entities.Scheduling", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<int>("Id médico")
                        .HasColumnType("int");

                    b.Property<int>("Id paciente")
                        .HasColumnType("int");

                    b.Property<DateTime>("appointment_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("appointment_end_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointment_start_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("order_id");

                    b.HasIndex("Id médico");

                    b.HasIndex("Id paciente");

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Appointment.Shared.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("bussiness_end_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bussiness_start_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("user_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Appointment.Shared.Entities.Scheduling", b =>
                {
                    b.HasOne("Appointment.Shared.Entities.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("Id médico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appointment.Shared.Entities.User", "Patient")
                        .WithMany()
                        .HasForeignKey("Id paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
